//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllData", ReplyAction="http://tempuri.org/IService1/GetAllDataResponse")]
        WcfServiceLibrary1.Employee[] GetAllData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllData", ReplyAction="http://tempuri.org/IService1/GetAllDataResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary1.Employee[]> GetAllDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingId", ReplyAction="http://tempuri.org/IService1/GetDataUsingIdResponse")]
        WcfServiceLibrary1.Employee GetDataUsingId(string email_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingId", ReplyAction="http://tempuri.org/IService1/GetDataUsingIdResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary1.Employee> GetDataUsingIdAsync(string email_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingType", ReplyAction="http://tempuri.org/IService1/GetDataUsingTypeResponse")]
        WcfServiceLibrary1.Employee[] GetDataUsingType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingType", ReplyAction="http://tempuri.org/IService1/GetDataUsingTypeResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary1.Employee[]> GetDataUsingTypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        bool AddEmployee(WcfServiceLibrary1.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        System.Threading.Tasks.Task<bool> AddEmployeeAsync(WcfServiceLibrary1.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditEmployee", ReplyAction="http://tempuri.org/IService1/EditEmployeeResponse")]
        bool EditEmployee(WcfServiceLibrary1.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditEmployee", ReplyAction="http://tempuri.org/IService1/EditEmployeeResponse")]
        System.Threading.Tasks.Task<bool> EditEmployeeAsync(WcfServiceLibrary1.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        bool DeleteEmployee(string email_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string email_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalary", ReplyAction="http://tempuri.org/IService1/GetSalaryResponse")]
        double GetSalary(string email_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalary", ReplyAction="http://tempuri.org/IService1/GetSalaryResponse")]
        System.Threading.Tasks.Task<double> GetSalaryAsync(string email_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary1.Employee[] GetAllData() {
            return base.Channel.GetAllData();
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary1.Employee[]> GetAllDataAsync() {
            return base.Channel.GetAllDataAsync();
        }
        
        public WcfServiceLibrary1.Employee GetDataUsingId(string email_id) {
            return base.Channel.GetDataUsingId(email_id);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary1.Employee> GetDataUsingIdAsync(string email_id) {
            return base.Channel.GetDataUsingIdAsync(email_id);
        }
        
        public WcfServiceLibrary1.Employee[] GetDataUsingType(string type) {
            return base.Channel.GetDataUsingType(type);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary1.Employee[]> GetDataUsingTypeAsync(string type) {
            return base.Channel.GetDataUsingTypeAsync(type);
        }
        
        public bool AddEmployee(WcfServiceLibrary1.Employee e) {
            return base.Channel.AddEmployee(e);
        }
        
        public System.Threading.Tasks.Task<bool> AddEmployeeAsync(WcfServiceLibrary1.Employee e) {
            return base.Channel.AddEmployeeAsync(e);
        }
        
        public bool EditEmployee(WcfServiceLibrary1.Employee e) {
            return base.Channel.EditEmployee(e);
        }
        
        public System.Threading.Tasks.Task<bool> EditEmployeeAsync(WcfServiceLibrary1.Employee e) {
            return base.Channel.EditEmployeeAsync(e);
        }
        
        public bool DeleteEmployee(string email_id) {
            return base.Channel.DeleteEmployee(email_id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string email_id) {
            return base.Channel.DeleteEmployeeAsync(email_id);
        }
        
        public double GetSalary(string email_id) {
            return base.Channel.GetSalary(email_id);
        }
        
        public System.Threading.Tasks.Task<double> GetSalaryAsync(string email_id) {
            return base.Channel.GetSalaryAsync(email_id);
        }
    }
}
